@baseUrl = http://127.0.0.1:8000

### Teste raiz (GET /)
GET {{baseUrl}}/

###

### Listar usuários (GET /usuarios)
GET {{baseUrl}}/usuarios

###

### Criar usuário (POST /usuarios)
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
  "nome": "João",
  "email": "joao@email.com"
}

###

### Login (POST /login)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "usuario": "admin",
  "senha": "123"
}